name: b001_from_scratch
target_size: &target_size !!python/tuple [128, 128, 128]
dbatch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path ./weights/morphade/
#
# Experiment
#
experiment:
  name: MORPHADE
  task: train
  weights: #'./weights/morphade/2023_11_06_12_47_02_702533/latest_model.pt'
#
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.morphaeus_3D
  class_name: MorphAEus
  params:
    inshape: *target_size
    bidir: True
    in_channels: 1
    nr_ref_channels: 3
    channels:
      - 32
      - 64
      - 128
      - 256
      - 512
     # - 1024
    strides:
    #  - 2
      - 2
      - 2
      - 2
      - 2
      - 2
    out_ch: 1
    kernel_size: 3
    norm: nos
    act: relu
    deconv_mode: stride_upsample
#
# Trainer
#
trainer:
  module_name: projects.morphade.MorphTrainer_3D_from_scratch
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    nr_epochs: 300
    max_iter: 100
    loss:
      module_name: optim.losses.ln_losses
      class_name: L2
      params:
    patience: 130
    alfa: 0.001
    beta: 0.01
    gamma: 0.01
    # Optimizer
    # Optimizer
    optimizer_params:
#      lr: 1.0e-4 # Orig
      lr: 5.0e-4
  # Data Loader
  data_loader:
# ADNI
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.brain3D_loader_adv
          class_name: Brain3DLoader
        data_dir:
          train:
          - './data/ADNI/cn_siem_3T_ww_train_registered.csv'
          val:
          - './data/ADNI/cn_siem_3T_ww_val_registered.csv'
          test:
          - './data/ADNI/cn_siem_3T_ww_test_registered.csv'
        target_size: *target_size
#        batch_size: 128 # Orig
        batch_size: 1
# Downstream tasks
downstream_tasks:
    detection:
      module_name: projects.morphade.DownstreamEvaluator
      class_name: PDownstreamEvaluator
      checkpoint_path: *checkpoint_path
      test_alzheimer: True
      data_loader:
        module_name: core.DataLoader
        class_name: DefaultDataLoader
        params:
          args:
            target_size: *target_size
            batch_size: *dbatch_size
            dataset_module:
          module_name: data.brain3D_loader_adv
          class_name: Brain3DLoader
        datasets:
          test_alzheimer:
            data_dir:
              test:
                - './data/ADNI/AD_Siem_3T_WW.csv'
 
    detection2:
      module_name: projects.morphade.DownstreamEvaluator
      class_name: PDownstreamEvaluator
      checkpoint_path: *checkpoint_path
      test_healthy: True
      data_loader:
        module_name: core.DataLoader
        class_name: DefaultDataLoader
        params:
          args:
            target_size: *target_size
            batch_size: *dbatch_size
            dataset_module:
          module_name: data.brain3D_loader_adv
          class_name: Brain3DLoader
        datasets:
          test_healthy:
            data_dir:
              test:
                - './data/ADNI/cn_siem_3T_ww_test_registered.csv'      
